apiVersion: v1
kind: Service
metadata:
  name: redis-service
  label:
    name: redis-service
    app: voting-app
  spec:
    ports:
      - port: 6379
        targetPort: 6379
    selector:
      name: redis-voting-app
      app: voting-app

