apiVersion: v1
kind: Pod
metadata:
  name: result-voting-app
  labels:
    name: result-voting-app
    app: voting-app
spec:
  containers:
    - name: result-voting-app
      image: dockersamples/examplevotingapp_result
    ports:
      - containerPort: 80
